<?php

namespace bausch\ticket;

use Yii;
use yii\helpers\Inflector;
use yii\helpers\ArrayHelper;

/**
 * It generated by module items .
 * 
 * @author Jairus Martin <jairusmartin@gmail.com>
 * @since x.x
 */
class Module extends \yii\base\Module
{
    /**
     * @var string Main layout using for module. Default to layout of parent module.
     * Its used when `layout` set to 'left-menu', 'right-menu' or 'top-menu'.
     */
    //public $mainLayout = '@mdm/admin/views/layouts/main.php';
    
}
